periodics:

- name: testing-periodics
  interval: 30m # Retest at most 1 PR per 30m
  decorate: true
  always_run: true
  max_concurrency: 5
  spec:
    containers:
    - image: alpine
      command:
      - "/bin/date"

presubmits:
  CiscoAI/kubeflow-test-infra:
  - name: presubmit-testing
    interval: 30m # Retest at most 1 PR per 30m
    decorate: true
    always_run: true
    max_concurrency: 5
    rerun_command: "/test testing-presubmit"
    trigger: "(?m)^/test( all| testing-presubmit),?(\\s+|$)"
    branches:
    - master
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20191210-5844d8374
        imagePullPolicy: Always
        command:
          - /checkconfig
        args:
          - --config-path=./prow/config.yaml
          - --job-config-path=./prow/prowjobs
          - --plugin-config=prow/plugins.yaml
          - --strict
          - --exclude-warning=mismatched-tide
          - --exclude-warning=non-decorated-jobs
