presubmits:
  CiscoAI/kubeflow-test-infra:
  - name: prow-config-validate
    #cluster: build
    decorate: true
    always_run: true
    max_concurrency: 5
    rerun_command: "/test test-presubmit"
    trigger: "(?m)^/test( all| test-presubmit),?(\\s+|$)"
    branches:
    - ^master$
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20191217-2b88bfc4b
        imagePullPolicy: Always
        command:
          - /checkconfig
        args:
          - --config-path=./prow/config.yaml
          - --job-config-path=./prow/prowjobs
          - --plugin-config=prow/plugins.yaml
          - --strict
          - --exclude-warning=mismatched-tide
          - --exclude-warning=non-decorated-jobs
